### PR TITLE
updated HTML page 2

### PR DESCRIPTION
**Pull request by bekahwhittle**
Updated my page for HTML!

### CODE REVIEW

**Comment by joebumbulis** [comment]
Looks great. One idea, take it or leave it:
Should the (or maybe you're planning this already) text about "Great choice...choose sword or spear" appear after they choose
Location? Or are you just hard coding it and then we'll use jquery to take the display on and off?

**Comment by bekahwhittle** [comment]
I was thinking of just hardcoding right now and then we can add a class "hidden" so to keep it simple!

**Comment by AndresTIY** [comment]
looks good to me!

**Comment by Spica8080** [comment]
This is Great Bek!!

**Pull request merged**
