### PR TITLE
started arch narrative

### PR DESCRIPTION
**Pull request by joebumbulis**
Look over the copy for the game arch. Give me some feedback if you have some ideas. I think that once we get to the battle sequence, we'll need more information for both the arch as well as the back and forth: when/what.

### CODE REVIEW

**Comment by joebumbulis** [comment]
[Create Copy for game](https://trello.com/c/aPvU1KGw/6-create-copy-for-game)

**Comment by bekahwhittle** [comment]
I like the story so thanks for telling us this! I think we should copy/paste these words to our pages while we're javascripting them btw!

**Comment by Spica8080** [comment]
LOVE it JOE!

**Comment by AndresTIY** [comment]
dope

**Pull request merged**
